version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: clientes-db
    environment:
      POSTGRES_DB: clientes
      POSTGRES_USER: clientes_user
      POSTGRES_PASSWORD: Maria123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
